In [9]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = a + b # Быстрое сложение массивов
result

array([5, 7, 9])

In [13]:
import numpy as np
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [15]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2 # [5, 7, 9]
result

array([5, 7, 9])

In [17]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2) # Матричное умножение
result

array([[19, 22],
       [43, 50]])

In [21]:
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data) # Среднее значение
std_dev = np.std(data) # Стандартное отклонение
mean

3.0

In [23]:
std_dev

1.4142135623730951

In [25]:
import numpy as np
arr = np.array([1, 2, 3, 4])
result = arr * 2 # Быстрое поэлементное умножение
result

array([2, 4, 6, 8])

In [33]:
import numpy as np
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m)
#[1 2 3 4]
#[5 6 7 8]
#[9 1 5 7]

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [35]:
m[1, 0]

5

In [37]:
m[1, :]

matrix([[5, 6, 7, 8]])

In [39]:
m[:, 2]

matrix([[3],
        [7],
        [5]])

In [41]:
m[1, 2:]

matrix([[7, 8]])

In [43]:
m[0:2, 1]

matrix([[2],
        [6]])

In [45]:
m[0:2, 1:3]

matrix([[2, 3],
        [6, 7]])

In [47]:
cols = [0, 1, 3]
m[:, cols]

matrix([[1, 2, 4],
        [5, 6, 8],
        [9, 1, 7]])

In [49]:
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [51]:
type(m)

numpy.matrix

In [53]:
m = np.array(m)
type(m)

numpy.ndarray

In [55]:
m.shape

(3, 4)

In [57]:
m.max()

9

In [59]:
np.max(m)

9

In [61]:
m.max(axis=1)

array([4, 8, 9])

In [64]:
m.max(axis=0)

array([9, 6, 7, 8])

In [66]:
m.mean()

4.833333333333333

In [68]:
m.mean(axis=1)

array([2.5, 6.5, 5.5])

In [70]:
m.sum()

58

In [72]:
m.sum(axis=0)

array([15,  9, 15, 19])

In [76]:
nums = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
letters = np.array(['a', 'b', 'c', 'd', 'a', 'e', 'b'])
nums

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
letters

array(['a', 'b', 'c', 'd', 'a', 'e', 'b'], dtype='<U1')

In [80]:
a = True

In [82]:
b = 5 > 7
print(b)

False


In [84]:
less_then_5 = nums < 5
less_then_5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [86]:
pos_a = letters == 'a'
pos_a

array([ True, False, False, False,  True, False, False])

In [88]:
less_then_5 = nums < 5
less_then_5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [90]:
nums[less_then_5]

array([1, 2, 3, 4])

In [92]:
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [94]:
mod_m = np.logical_and(m>=3, m<=7)
mod_m

matrix([[False, False,  True,  True],
        [ True,  True,  True, False],
        [False, False,  True,  True]])

In [96]:
m[mod_m]

matrix([[3, 4, 5, 6, 7, 5, 7]])

In [98]:
nums = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
nums[nums < 5]

array([1, 2, 3, 4])

In [100]:
nums[nums < 5] = 10
print(nums)

[10 10 10 10  5  6  7  8  9 10]


In [102]:
m[m > 7] = 25
print(m)

[[ 1  2  3  4]
 [ 5  6  7 25]
 [25  1  5  7]]


In [104]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
np.arange(5, 12)

array([ 5,  6,  7,  8,  9, 10, 11])

In [108]:
np.arange(1, 5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [110]:
a = [[1, 2], [3, 4]]
np.matrix(a)

matrix([[1, 2],
        [3, 4]])

In [112]:
b = np.array([[5, 6], [7, 8]])
np.matrix(b)

matrix([[5, 6],
        [7, 8]])

In [118]:
np.matrix('[1, 2; 3, 4]')

matrix([[1, 2],
        [3, 4]])

In [120]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [122]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [124]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [126]:
np.ravel(A)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
np.ravel(A, order='C')

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
np.ravel(A, order='F')

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [132]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.where(a % 2 == 0, a * 10, a / 10)

array([ 0. ,  0.1, 20. ,  0.3, 40. ,  0.5, 60. ,  0.7, 80. ,  0.9])

In [134]:
a = np.random.rand(10)
a

array([0.3262295 , 0.98663784, 0.90349875, 0.65280153, 0.40897622,
       0.96146321, 0.37197292, 0.19502023, 0.84277196, 0.07992483])

In [136]:
np.where(a > 0.5, True, False)

array([False,  True,  True,  True, False,  True, False, False,  True,
       False])

In [138]:
np.where(a > 0.5, 1, -1)

array([-1,  1,  1,  1, -1,  1, -1, -1,  1, -1])

In [140]:
x = np.linspace(0, 1, 5)
x

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [142]:
y = np.linspace(0, 2, 5)
y

array([0. , 0.5, 1. , 1.5, 2. ])

In [144]:
xg, yg = np.meshgrid(x, y)
xg

array([[0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ]])

In [146]:
yg

array([[0. , 0. , 0. , 0. , 0. ],
       [0.5, 0.5, 0.5, 0.5, 0.5],
       [1. , 1. , 1. , 1. , 1. ],
       [1.5, 1.5, 1.5, 1.5, 1.5],
       [2. , 2. , 2. , 2. , 2. ]])

In [152]:
import matplotlib.pyplot as plt
%matplotlib inline

In [150]:

plt.plot(xg, yg, color="r", marker="*", linestyle="none")

In [158]:
plt.plot(xg, yg, color="r", marker="*", linestyle="none")
plt.show()

In [160]:
np.random.permutation(7)

array([0, 3, 2, 5, 6, 1, 4])

In [164]:
a = ['a', 'b', 'c', 'd', 'e']
np.random.permutation(a)

array(['a', 'd', 'b', 'c', 'e'], dtype='<U1')

In [166]:
arr = np.linspace(0, 10, 5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [168]:
arr_mix = np.random.permutation(arr)
arr_mix

array([ 7.5, 10. ,  0. ,  2.5,  5. ])

In [170]:
index_mix = np.random.permutation(len(arr_mix))
index_mix


array([3, 4, 1, 2, 0])

In [172]:
arr[index_mix]

array([ 7.5, 10. ,  2.5,  5. ,  0. ])

In [174]:
import numpy as np

In [176]:
v_hor_np = np.array([1, 2])
print(v_hor_np )

[1 2]


In [178]:
v_hor_zeros_v1 = np.zeros((5,))
print(v_hor_zeros_v1 )

[0. 0. 0. 0. 0.]


In [180]:
v_hor_zeros_v2 = np.zeros((1, 5))
print(v_hor_zeros_v2 )

[[0. 0. 0. 0. 0.]]


In [182]:
v_hor_one_v1 = np.ones((5,))
print(v_hor_one_v1)

[1. 1. 1. 1. 1.]


In [184]:
v_hor_one_v2 = np.ones((1, 5))
print(v_hor_one_v2)

[[1. 1. 1. 1. 1.]]


In [186]:
v_vert_np = np.array([[1], [2]])
print(v_vert_np)

[[1]
 [2]]


In [188]:
v_vert_zeros = np.zeros((5, 1))
print(v_vert_zeros)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [190]:
v_vert_ones = np.ones((5, 1))
print(v_vert_ones)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [192]:
m_sqr_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m_sqr_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [194]:
m_sqr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
m_sqr_arr = np.array(m_sqr)
print(m_sqr_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [196]:
m_sqr_mx = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m_sqr_mx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [198]:
m_sqr_mx = np.matrix('1 2 3; 4 5 6; 7 8 9')
print(m_sqr_mx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [200]:
m_diag = [[1, 0, 0], [0, 5, 0], [0, 0, 9]]
m_diag_np = np.matrix(m_diag)
print(m_diag_np)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [206]:
m_sqr_mx = np.matrix('1 2 3; 4 5 6; 7 8 9')
m_sqr_mx

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [208]:
diag = np.diag(m_sqr_mx)
print(diag)

[1 5 9]


In [210]:
m_diag_np = np.diag(np.diag(m_sqr_mx))
print(m_diag_np)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [212]:
m_e = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
m_e_np = np.matrix(m_e)
print(m_e_np)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [214]:
m_eye = np.eye(3)
print(m_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [216]:
m_idnt = np.identity(3)
print(m_idnt)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [218]:
m_zeros = np.zeros((3, 3))
print(m_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [222]:
m_mx = np.matrix('1 2 3; 4 5 6')
print(m_mx)

[[1 2 3]
 [4 5 6]]


In [224]:
m_var = np.zeros((2, 5))
print(m_var)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [226]:
A = np.matrix('1 2 3; 4 5 6')
print(A)

[[1 2 3]
 [4 5 6]]


In [228]:
A_t = A.transpose()
print(A_t)

[[1 4]
 [2 5]
 [3 6]]


In [230]:
print(A.T)

[[1 4]
 [2 5]
 [3 6]]


In [232]:
A = np.matrix('1 2 3; 4 5 6')
print(A)

[[1 2 3]
 [4 5 6]]


In [234]:
R = (A.T).T
print(R)

[[1 2 3]
 [4 5 6]]


In [236]:
A = np.matrix('1 2 3; 4 5 6')
B = np.matrix('7 8 9; 0 7 5')
L = (A + B).T
R = A.T + B.T
print(L)

[[ 8  4]
 [10 12]
 [12 11]]


In [238]:
print(R)

[[ 8  4]
 [10 12]
 [12 11]]


In [240]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
L = (A.dot(B)).T
R = (B.T).dot(A.T)
print(L)

[[19 43]
 [22 50]]


In [242]:
print(R)

[[19 43]
 [22 50]]


In [244]:
A = np.matrix('1 2 3; 4 5 6')
k = 3
L = (k * A).T
R = k * (A.T)
print(L)

[[ 3 12]
 [ 6 15]
 [ 9 18]]


In [246]:
print(R)

[[ 3 12]
 [ 6 15]
 [ 9 18]]


In [248]:
A = np.matrix('1 2; 3 4')
A_det = np.linalg.det(A)
A_T_det = np.linalg.det(A.T)
print(f"{A_det:.9f}")

-2.000000000


In [250]:
print(f"{A_T_det:.9f}")

-2.000000000


In [252]:
A = np.matrix('1 2 3; 4 5 6')
C = 3 * A
print(C)

[[ 3  6  9]
 [12 15 18]]


In [254]:
A = np.matrix('1 2; 3 4')
L = 1 * A
R = A
print(L)

[[1 2]
 [3 4]]


In [256]:
print(R)

[[1 2]
 [3 4]]


In [258]:
A = np.matrix('1 2; 3 4')
Z = np.matrix('0 0; 0 0')
L = 0 * A
R = Z
print(L)

[[0 0]
 [0 0]]


In [260]:
A = np.matrix('1 2; 3 4')
p = 2
q = 3
L = (p + q) * A
R = p * A + q * A
print(L)

[[ 5 10]
 [15 20]]


In [262]:
print(R)

[[ 5 10]
 [15 20]]


In [264]:
A = np.matrix('1 2; 3 4')
p = 2
q = 3
L = (p * q) * A
R = p * (q * A)
print(L)

[[ 6 12]
 [18 24]]


In [266]:
print(R)

[[ 6 12]
 [18 24]]


In [268]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
k = 3
L = k * (A + B)
R = k * A + k * B
print(L)

[[18 24]
 [30 36]]


In [270]:
print(R)

[[18 24]
 [30 36]]


In [272]:
A = np.matrix('1 6 3; 8 2 7')
B = np.matrix('8 1 5; 6 9 12')
C = A + B
print(C)

[[ 9  7  8]
 [14 11 19]]


In [274]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
L = A + B
R = B + A
print(L)

[[ 6  8]
 [10 12]]


In [276]:
print(R)

[[ 6  8]
 [10 12]]


In [278]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('1 7; 9 3')
L = A + (B + C)
R = (A + B) + C
print(L)

[[ 7 15]
 [19 15]]


In [280]:
print(R)

[[ 7 15]
 [19 15]]


In [282]:
A = np.matrix('1 2 3; 4 5 6')
B = np.matrix('7 8; 9 1; 2 3')
C = A.dot(B)
print(C)

[[31 19]
 [85 55]]


In [284]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('2 4; 7 8')
L = A.dot(B.dot(C))
R = (A.dot(B)).dot(C)
print(L)

[[192 252]
 [436 572]]


In [286]:
print(R)

[[192 252]
 [436 572]]


In [288]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('2 4; 7 8')
L = A.dot(B + C)
R = A.dot(B) + A.dot(C)
print(L)

[[35 42]
 [77 94]]


In [290]:
print(R)

[[35 42]
 [77 94]]


In [292]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
L = A.dot(B)
R = B.dot(A)
print(L)

[[19 22]
 [43 50]]


In [294]:
print(R)

[[23 34]
 [31 46]]


In [296]:
A = np.matrix('1 2; 3 4')
E = np.matrix('1 0; 0 1')
L = E.dot(A)
R = A.dot(E)
print(L)

[[1 2]
 [3 4]]


In [298]:
print(R)

[[1 2]
 [3 4]]


In [300]:
print(A)

[[1 2]
 [3 4]]


In [302]:
A = np.matrix('1 2; 3 4')
Z = np.matrix('0 0; 0 0')
L = Z.dot(A)
R = A.dot(Z)
print(L)

[[0 0]
 [0 0]]


In [304]:
print(R)

[[0 0]
 [0 0]]


In [306]:
print(Z)

[[0 0]
 [0 0]]


In [308]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [310]:
np.linalg.det(A)

-14.000000000000009

In [314]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [316]:
print(A.T)

[[-4 10  8]
 [-1  4  3]
 [ 2 -1  1]]


In [318]:
det_A = round(np.linalg.det(A), 3)
det_A_t = round(np.linalg.det(A.T), 3)
print(det_A)

-14.0


In [320]:
print(det_A_t)

-14.0


In [322]:
A = np.matrix('-4 -1 2; 0 0 0; 8 3 1')
print(A)

[[-4 -1  2]
 [ 0  0  0]
 [ 8  3  1]]


In [324]:
np.linalg.det(A)

0.0

In [326]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [328]:
B = np.matrix('10 4 -1; -4 -1 2; 8 3 1')
print(B)

[[10  4 -1]
 [-4 -1  2]
 [ 8  3  1]]


In [330]:
round(np.linalg.det(A), 3)

-14.0

In [332]:
round(np.linalg.det(B), 3)

14.0

In [334]:
A = np.matrix('-4 -1 2; -4 -1 2; 8 3 1')
print(A)

[[-4 -1  2]
 [-4 -1  2]
 [ 8  3  1]]


In [336]:
np.linalg.det(A)

0.0

In [338]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [340]:
k = 2
B = A.copy()
B[2, :] = k * B[2, :]
print(B)

[[-4 -1  2]
 [10  4 -1]
 [16  6  2]]


In [342]:
det_A = round(np.linalg.det(A), 3)
det_B = round(np.linalg.det(B), 3)
det_A * k

-28.0

In [344]:
det_B

-28.0

In [346]:
A = np.matrix('-4 -1 2; -4 -1 2; 8 3 1')
B = np.matrix('-4 -1 2; 8 3 2; 8 3 1')
C = A.copy()
C[1, :] += B[1, :]
print(C)

[[-4 -1  2]
 [ 4  2  4]
 [ 8  3  1]]


In [348]:
print(A)

[[-4 -1  2]
 [-4 -1  2]
 [ 8  3  1]]


In [350]:
print(B)

[[-4 -1  2]
 [ 8  3  2]
 [ 8  3  1]]


In [352]:
round(np.linalg.det(C), 3)

4.0

In [354]:
round(np.linalg.det(A), 3) + round(np.linalg.det(B), 3)

4.0

In [356]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
k = 2
B = A.copy()
B[1, :] = B[1, :] + k * B[0, :]
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [358]:
print(B)

[[-4 -1  2]
 [ 2  2  3]
 [ 8  3  1]]


In [360]:
round(np.linalg.det(A), 3)

-14.0

In [362]:
round(np.linalg.det(B), 3)

-14.0

In [364]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [366]:
k = 2
A[1, :] = A[0, :] + k * A[2, :]
round(np.linalg.det(A), 3)

0.0

In [368]:
A = np.matrix('1 -3; 2 5')
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.45454545  0.27272727]
 [-0.18181818  0.09090909]]


In [370]:
A = np.matrix('1. -3.; 2. 5.')
A_inv = np.linalg.inv(A)
A_inv_inv = np.linalg.inv(A_inv)
print(A)

[[ 1. -3.]
 [ 2.  5.]]


In [372]:
print(A_inv_inv)

[[ 1. -3.]
 [ 2.  5.]]


In [374]:
A = np.matrix('1. -3.; 2. 5.')
L = np.linalg.inv(A.T)
R = (np.linalg.inv(A)).T
print(L)

[[ 0.45454545 -0.18181818]
 [ 0.27272727  0.09090909]]


In [376]:
print(R)

[[ 0.45454545 -0.18181818]
 [ 0.27272727  0.09090909]]


In [378]:
A = np.matrix('1. -3.; 2. 5.')
B = np.matrix('7. 6.; 1. 8.')
L = np.linalg.inv(A.dot(B))
R = np.linalg.inv(B).dot(np.linalg.inv(A))
print(L)

[[ 0.09454545  0.03272727]
 [-0.03454545  0.00727273]]


In [380]:
print(R)

[[ 0.09454545  0.03272727]
 [-0.03454545  0.00727273]]


In [382]:
m_eye = np.eye(4)
print(m_eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [384]:
rank = np.linalg.matrix_rank(m_eye)
print(rank)

4


In [386]:
m_eye[3][3] = 0
print(m_eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]


In [388]:
rank = np.linalg.matrix_rank(m_eye)
print(rank)

3
